-- V8: Enhanced Panchayat Website Templates with Comprehensive Sections
-- This migration creates 9 professional templates (3 per language) with 12-14 sections each
-- Includes: Hero, Services, Statistics, News, Gallery, Social Media, and more
-- Each template uses image placeholders and professional color themes

-- Ensure is_page_template column exists (in case V5-V7 haven't run)
DO $$ 
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns 
        WHERE table_name = 'section_templates' 
        AND column_name = 'is_page_template'
    ) THEN
        ALTER TABLE section_templates 
        ADD COLUMN is_page_template BOOLEAN NOT NULL DEFAULT false;
    END IF;
END $$;

-- Delete old templates to ensure clean slate
DELETE FROM section_templates 
WHERE (name LIKE '%Professional Government Services%' 
   OR name LIKE '%Modern Community Portal%' 
   OR name LIKE '%Elegant Public Services%'
   OR name LIKE '%पेशेवर सरकारी सेवाएं%'
   OR name LIKE '%व्यावसायिक सरकारी सेवा%'
   OR name LIKE '%आधुनिक सामुदायिक पोर्टल%'
   OR name LIKE '%आधुनिक समुदाय पोर्टल%'
   OR name LIKE '%सुरुचिपूर्ण सार्वजनिक सेवा%'
   OR name LIKE '%सुरुचिपूर्ण सार्वजनिक सेवाएं%')
  AND is_page_template = true;

-- ============================================================================
-- TEMPLATE 1: Professional Government Services
-- Color Theme: Professional Blue (#1e3a8a, #f8fafc)
-- Sections: 13 sections including Hero, Services, Statistics, News, Gallery, Social Media
-- ============================================================================

-- Template 1.1: Professional Government Services (English) - 13 sections
INSERT INTO section_templates (name, description, category, language, template_data, color_theme, display_order, is_active, is_system, is_page_template) 
SELECT 'Professional Government Services', 'Complete panchayat website template with 13 pre-configured sections including Hero Carousel, Services, Statistics, News, Gallery, and Social Media - Professional Blue Theme', 'Full Page', 'en',
'{"sections":[
  {"sectionType":"HERO_BANNER","layoutType":"CAROUSEL","title":"Welcome to [Panchayat Name]","subtitle":"Building a self-reliant, digitally empowered, and sustainable village","content":{"items":[{"id":"hero-1","title":"Welcome to Our Digital Panchayat","description":"Transparent governance for a better tomorrow","image":"https://via.placeholder.com/1920x1080/1e3a8a/ffffff?text=Welcome+to+Panchayat","link":"#about"},{"id":"hero-2","title":"Digital Services","description":"Access government services online","image":"https://via.placeholder.com/1920x1080/3b82f6/ffffff?text=Digital+Services","link":"#services"},{"id":"hero-3","title":"Community Development","description":"Building infrastructure for tomorrow","image":"https://via.placeholder.com/1920x1080/60a5fa/ffffff?text=Development","link":"#projects"}],"carouselConfig":{"layoutType":"single","indicatorType":"dots","itemsPerView":1,"autoPlay":true,"interval":5000,"pauseOnHover":true,"loop":true,"showArrows":true,"showIndicators":true}},"backgroundColor":"#1e3a8a","textColor":"#ffffff","isVisible":true,"displayOrder":0},
  {"sectionType":"STATISTICS_SECTION","layoutType":"GRID","title":"Our Village at a Glance","subtitle":"Real-time demographic and development data","content":{"items":[{"id":"stat-1","type":"stat","title":"Total Population","value":"5000+","label":"Residents","icon":"users"},{"id":"stat-2","type":"stat","title":"Total Households","value":"1200+","label":"Families","icon":"building"},{"id":"stat-3","type":"stat","title":"Area Coverage","value":"25","label":"Square Kilometers","icon":"map-pin"},{"id":"stat-4","type":"stat","title":"Projects Completed","value":"45+","label":"This Year","icon":"award"}],"columns":4},"backgroundColor":"#f8fafc","textColor":"#1e293b","isVisible":true,"displayOrder":1},
  {"sectionType":"CARD_SECTION","layoutType":"GRID","title":"Citizen Services & Welfare Schemes","subtitle":"Empowering rural communities through government initiatives","content":{"items":[{"id":"service-1","type":"card","title":"Birth Certificate","description":"Apply for birth certificates and registration services online.","icon":"file-text","link":"#","image":"https://via.placeholder.com/400x300/3b82f6/ffffff?text=Birth+Certificate"},{"id":"service-2","type":"card","title":"Death Certificate","description":"Obtain death certificates and related documentation.","icon":"file-text","link":"#","image":"https://via.placeholder.com/400x300/3b82f6/ffffff?text=Death+Certificate"},{"id":"service-3","type":"card","title":"PM Awas Yojana","description":"Housing scheme for rural development and affordable housing.","icon":"home","link":"#","image":"https://via.placeholder.com/400x300/3b82f6/ffffff?text=PM+Awas"},{"id":"service-4","type":"card","title":"MGNREGA","description":"Employment guarantee scheme for rural workers.","icon":"briefcase","link":"#","image":"https://via.placeholder.com/400x300/3b82f6/ffffff?text=MGNREGA"},{"id":"service-5","type":"card","title":"Swachh Bharat","description":"Clean India mission for sanitation and hygiene.","icon":"trash","link":"#","image":"https://via.placeholder.com/400x300/3b82f6/ffffff?text=Swachh+Bharat"},{"id":"service-6","type":"card","title":"Ayushman Bharat","description":"Health insurance scheme for all citizens.","icon":"heart","link":"#","image":"https://via.placeholder.com/400x300/3b82f6/ffffff?text=Ayushman"},{"id":"service-7","type":"card","title":"PM Kisan","description":"Direct income support for farmers.","icon":"tractor","link":"#","image":"https://via.placeholder.com/400x300/3b82f6/ffffff?text=PM+Kisan"},{"id":"service-8","type":"card","title":"SVAMITVA","description":"Property mapping and digital property cards.","icon":"map","link":"#","image":"https://via.placeholder.com/400x300/3b82f6/ffffff?text=SVAMITVA"}],"columns":4},"backgroundColor":"#ffffff","textColor":"#1e293b","isVisible":true,"displayOrder":2},
  {"sectionType":"TEAM_MEMBERS","layoutType":"GRID","title":"Our Elected Representatives","subtitle":"Serving the community with dedication","content":{"items":[{"id":"member-1","type":"card","title":"Sarpanch","subtitle":"[Sarpanch Name]","description":"Chief of the Panchayat, leading community development initiatives.","image":"https://via.placeholder.com/300x300/1e3a8a/ffffff?text=Sarpanch","link":"#"},{"id":"member-2","type":"card","title":"Up-Sarpanch","subtitle":"[Up-Sarpanch Name]","description":"Deputy Sarpanch supporting governance and administration.","image":"https://via.placeholder.com/300x300/3b82f6/ffffff?text=Up-Sarpanch","link":"#"},{"id":"member-3","type":"card","title":"Ward Member","subtitle":"[Ward Member Name]","description":"Representing ward interests in panchayat decisions.","image":"https://via.placeholder.com/300x300/60a5fa/ffffff?text=Ward+Member","link":"#"}],"columns":3},"backgroundColor":"#f8fafc","textColor":"#1e293b","isVisible":true,"displayOrder":3},
  {"sectionType":"IMAGE_GALLERY","layoutType":"CAROUSEL","title":"Development Works & Projects","subtitle":"Ongoing and completed infrastructure projects","content":{"items":[{"id":"project-1","type":"gallery_item","title":"Road Construction","description":"New road connecting village to main highway","image":"https://via.placeholder.com/800x600/1e3a8a/ffffff?text=Road+Project"},{"id":"project-2","type":"gallery_item","title":"Water Supply","description":"Overhead tank installation for better water access","image":"https://via.placeholder.com/800x600/3b82f6/ffffff?text=Water+Project"},{"id":"project-3","type":"gallery_item","title":"School Building","description":"New school building for quality education","image":"https://via.placeholder.com/800x600/60a5fa/ffffff?text=School+Project"}],"carouselConfig":{"layoutType":"multi","indicatorType":"dots","itemsPerView":3,"itemsPerViewTablet":2,"itemsPerViewMobile":1,"autoPlay":true,"interval":4000,"pauseOnHover":true,"loop":true,"showArrows":true,"showIndicators":true}},"backgroundColor":"#ffffff","textColor":"#1e293b","isVisible":true,"displayOrder":4},
  {"sectionType":"NEWS_FEED","layoutType":"GRID","title":"Latest News & Announcements","subtitle":"Stay informed about village activities","content":{"items":[{"id":"news-1","type":"card","title":"Gram Sabha Meeting","subtitle":"15th of this month","description":"Monthly Gram Sabha meeting to discuss village development and citizen concerns.","image":"https://via.placeholder.com/400x300/1e3a8a/ffffff?text=Gram+Sabha","link":"#"},{"id":"news-2","type":"card","title":"Government Scheme Applications","subtitle":"Deadline: End of month","description":"Apply for PM Awas Yojana and other welfare schemes. Forms available at panchayat office.","image":"https://via.placeholder.com/400x300/3b82f6/ffffff?text=Schemes","link":"#"},{"id":"news-3","type":"card","title":"Health Camp","subtitle":"Next week","description":"Free health checkup camp organized by health department. All citizens welcome.","image":"https://via.placeholder.com/400x300/60a5fa/ffffff?text=Health+Camp","link":"#"}],"columns":3},"backgroundColor":"#f8fafc","textColor":"#1e293b","isVisible":true,"displayOrder":5},
  {"sectionType":"IMAGE_WITH_TEXT","layoutType":"SPLIT","title":"About Our Panchayat","subtitle":"Serving the Community","content":{"content":"We are dedicated to providing transparent, efficient, and citizen-centric governance. Our mission is to empower every citizen through digital services, community engagement, and sustainable development initiatives. We believe in participatory democracy and work closely with the community to address their needs and aspirations.","image":"https://via.placeholder.com/800x600/1e3a8a/ffffff?text=About+Us","imagePosition":"left"},"backgroundColor":"#ffffff","textColor":"#1e293b","isVisible":true,"displayOrder":6},
  {"sectionType":"CARD_SECTION","layoutType":"ROW","title":"Public Facilities & Infrastructure","subtitle":"Essential services for community development","content":{"items":[{"id":"facility-1","type":"card","title":"Primary School","description":"Quality education for children","icon":"book","link":"#","image":"https://via.placeholder.com/300x200/1e3a8a/ffffff?text=School"},{"id":"facility-2","type":"card","title":"Health Center","description":"Primary healthcare services","icon":"heart","link":"#","image":"https://via.placeholder.com/300x200/3b82f6/ffffff?text=Health"},{"id":"facility-3","type":"card","title":"Community Hall","description":"Venue for events and meetings","icon":"users","link":"#","image":"https://via.placeholder.com/300x200/60a5fa/ffffff?text=Hall"}],"columns":3},"backgroundColor":"#f8fafc","textColor":"#1e293b","isVisible":true,"displayOrder":7},
  {"sectionType":"PARAGRAPH_CONTENT","layoutType":"CONTAINED","title":"Citizen Grievance Redressal System","subtitle":"Your voice matters - We listen, we act","content":{"richText":"<p>We have established a comprehensive grievance redressal system to address citizen concerns promptly. You can file complaints online or visit the panchayat office. We aim to resolve all grievances within 15-30 days.</p><p><strong>How to file a complaint:</strong></p><ul><li>Online: Visit our website and use the complaint form</li><li>Offline: Submit written complaint at panchayat office</li><li>Helpline: Call our toll-free number during office hours</li></ul><p><strong>Expected resolution time:</strong> 15-30 days</p>"},"backgroundColor":"#1e3a8a","textColor":"#ffffff","isVisible":true,"displayOrder":8},
  {"sectionType":"CARD_SECTION","layoutType":"GRID","title":"Right to Information & Transparency","subtitle":"Promoting accountability in governance","content":{"items":[{"id":"rti-1","type":"card","title":"RTI Corner","description":"How to file RTI, PIO details, and fee structure","icon":"file-text","link":"#","image":"https://via.placeholder.com/400x300/1e3a8a/ffffff?text=RTI"},{"id":"rti-2","type":"card","title":"Financial Transparency","description":"Budget documents, expenditure reports, and audit reports","icon":"dollar-sign","link":"#","image":"https://via.placeholder.com/400x300/3b82f6/ffffff?text=Finance"},{"id":"rti-3","type":"card","title":"GPDP Plan","description":"Gram Panchayat Development Plan for current year","icon":"calendar","link":"#","image":"https://via.placeholder.com/400x300/60a5fa/ffffff?text=GPDP"},{"id":"rti-4","type":"card","title":"Tender & Contracts","description":"Active tenders and awarded contracts","icon":"file","link":"#","image":"https://via.placeholder.com/400x300/1e3a8a/ffffff?text=Tenders"}],"columns":4},"backgroundColor":"#ffffff","textColor":"#1e293b","isVisible":true,"displayOrder":9},
  {"sectionType":"CARD_SECTION","layoutType":"GRID","title":"Important Links & Quick Access","subtitle":"Essential information at your fingertips","content":{"items":[{"id":"link-1","type":"card","title":"eGramSwaraj Portal","description":"Digital panchayat dashboard and services","icon":"globe","link":"https://egramswaraj.gov.in","image":"https://via.placeholder.com/300x200/1e3a8a/ffffff?text=eGramSwaraj"},{"id":"link-2","type":"card","title":"SVAMITVA Portal","description":"Property mapping and digital property cards","icon":"map","link":"https://svamitva.gov.in","image":"https://via.placeholder.com/300x200/3b82f6/ffffff?text=SVAMITVA"},{"id":"link-3","type":"card","title":"MGNREGA Portal","description":"Employment guarantee scheme information","icon":"briefcase","link":"https://nrega.nic.in","image":"https://via.placeholder.com/300x200/60a5fa/ffffff?text=MGNREGA"},{"id":"link-4","type":"card","title":"Ministry of Panchayati Raj","description":"Official government portal for panchayats","icon":"building","link":"https://panchayat.gov.in","image":"https://via.placeholder.com/300x200/1e3a8a/ffffff?text=Ministry"}],"columns":4},"backgroundColor":"#f8fafc","textColor":"#1e293b","isVisible":true,"displayOrder":10},
  {"sectionType":"TIMELINE_SECTION","layoutType":"LIST","title":"Upcoming Events & Gram Sabha","subtitle":"Participate in local governance","content":{"items":[{"id":"event-1","type":"timeline_item","title":"Gram Sabha Meeting","subtitle":"26th January","description":"Republic Day Gram Sabha meeting to discuss annual development plan and budget allocation."},{"id":"event-2","type":"timeline_item","title":"Health Camp","subtitle":"First week of next month","description":"Free health checkup and vaccination camp for all citizens."},{"id":"event-3","type":"timeline_item","title":"Cultural Festival","subtitle":"Mid-month","description":"Annual village cultural festival celebrating local traditions and heritage."}],"columns":1},"backgroundColor":"#ffffff","textColor":"#1e293b","isVisible":true,"displayOrder":11},
  {"sectionType":"CARD_SECTION","layoutType":"ROW","title":"Connect With Us","subtitle":"Follow us on social media","content":{"items":[{"id":"social-1","type":"card","title":"Facebook","description":"Like our page for updates","icon":"facebook","link":"https://facebook.com/panchayat","image":"https://via.placeholder.com/64x64/1877f2/ffffff?text=FB"},{"id":"social-2","type":"card","title":"Twitter","description":"Follow us for news","icon":"twitter","link":"https://twitter.com/panchayat","image":"https://via.placeholder.com/64x64/1da1f2/ffffff?text=TW"},{"id":"social-3","type":"card","title":"YouTube","description":"Subscribe to our channel","icon":"youtube","link":"https://youtube.com/panchayat","image":"https://via.placeholder.com/64x64/ff0000/ffffff?text=YT"},{"id":"social-4","type":"card","title":"WhatsApp","description":"Join our group","icon":"message-circle","link":"https://wa.me/1234567890","image":"https://via.placeholder.com/64x64/25d366/ffffff?text=WA"}],"columns":4},"backgroundColor":"#f8fafc","textColor":"#1e293b","isVisible":true,"displayOrder":12}
]}',
'professional-blue', 1, true, true, true
WHERE NOT EXISTS (SELECT 1 FROM section_templates WHERE name = 'Professional Government Services' AND language = 'en' AND is_page_template = true);

-- Template 1.2: Professional Government Services (Hindi) - 13 sections
INSERT INTO section_templates (name, description, category, language, template_data, color_theme, display_order, is_active, is_system, is_page_template) 
SELECT 'पेशेवर सरकारी सेवाएं', '13 पूर्व-कॉन्फ़िगर किए गए सेक्शन के साथ पूर्ण पंचायत वेबसाइट टेम्प्लेट जिसमें हीरो कैरोसेल, सेवाएं, आंकड़े, समाचार, गैलरी और सोशल मीडिया शामिल है - पेशेवर ब्लू थीम', 'Full Page', 'hi',
'{"sections":[
  {"sectionType":"HERO_BANNER","layoutType":"CAROUSEL","title":"[पंचायत नाम] में आपका स्वागत है","subtitle":"एक आत्मनिर्भर, डिजिटल रूप से सशक्त और स्थायी गांव का निर्माण","content":{"items":[{"id":"hero-1","title":"हमारे डिजिटल पंचायत में आपका स्वागत है","description":"बेहतर कल के लिए पारदर्शी शासन","image":"https://via.placeholder.com/1920x1080/1e3a8a/ffffff?text=पंचायत+में+स्वागत","link":"#about"},{"id":"hero-2","title":"डिजिटल सेवाएं","description":"ऑनलाइन सरकारी सेवाओं तक पहुंच","image":"https://via.placeholder.com/1920x1080/3b82f6/ffffff?text=डिजिटल+सेवाएं","link":"#services"},{"id":"hero-3","title":"सामुदायिक विकास","description":"कल के लिए बुनियादी ढांचा बनाना","image":"https://via.placeholder.com/1920x1080/60a5fa/ffffff?text=विकास","link":"#projects"}],"carouselConfig":{"layoutType":"single","indicatorType":"dots","itemsPerView":1,"autoPlay":true,"interval":5000,"pauseOnHover":true,"loop":true,"showArrows":true,"showIndicators":true}},"backgroundColor":"#1e3a8a","textColor":"#ffffff","isVisible":true,"displayOrder":0},
  {"sectionType":"STATISTICS_SECTION","layoutType":"GRID","title":"एक नज़र में हमारा गांव","subtitle":"वास्तविक समय जनसांख्यिकी और विकास डेटा","content":{"items":[{"id":"stat-1","type":"stat","title":"कुल जनसंख्या","value":"5000+","label":"निवासी","icon":"users"},{"id":"stat-2","type":"stat","title":"कुल परिवार","value":"1200+","label":"परिवार","icon":"building"},{"id":"stat-3","type":"stat","title":"क्षेत्र कवरेज","value":"25","label":"वर्ग किलोमीटर","icon":"map-pin"},{"id":"stat-4","type":"stat","title":"पूर्ण परियोजनाएं","value":"45+","label":"इस वर्ष","icon":"award"}],"columns":4},"backgroundColor":"#f8fafc","textColor":"#1e293b","isVisible":true,"displayOrder":1},
  {"sectionType":"CARD_SECTION","layoutType":"GRID","title":"नागरिक सेवाएं और कल्याण योजनाएं","subtitle":"सरकारी पहलों के माध्यम से ग्रामीण समुदायों को सशक्त बनाना","content":{"items":[{"id":"service-1","type":"card","title":"जन्म प्रमाणपत्र","description":"ऑनलाइन जन्म प्रमाणपत्र और पंजीकरण सेवाओं के लिए आवेदन करें।","icon":"file-text","link":"#","image":"https://via.placeholder.com/400x300/3b82f6/ffffff?text=जन्म+प्रमाणपत्र"},{"id":"service-2","type":"card","title":"मृत्यु प्रमाणपत्र","description":"मृत्यु प्रमाणपत्र और संबंधित दस्तावेज प्राप्त करें।","icon":"file-text","link":"#","image":"https://via.placeholder.com/400x300/3b82f6/ffffff?text=मृत्यु+प्रमाणपत्र"},{"id":"service-3","type":"card","title":"पीएम आवास योजना","description":"ग्रामीण विकास और सस्ती आवास के लिए आवास योजना।","icon":"home","link":"#","image":"https://via.placeholder.com/400x300/3b82f6/ffffff?text=PM+आवास"},{"id":"service-4","type":"card","title":"मनरेगा","description":"ग्रामीण श्रमिकों के लिए रोजगार गारंटी योजना।","icon":"briefcase","link":"#","image":"https://via.placeholder.com/400x300/3b82f6/ffffff?text=मनरेगा"},{"id":"service-5","type":"card","title":"स्वच्छ भारत","description":"स्वच्छता और स्वच्छता के लिए स्वच्छ भारत मिशन।","icon":"trash","link":"#","image":"https://via.placeholder.com/400x300/3b82f6/ffffff?text=स्वच्छ+भारत"},{"id":"service-6","type":"card","title":"आयुष्मान भारत","description":"सभी नागरिकों के लिए स्वास्थ्य बीमा योजना।","icon":"heart","link":"#","image":"https://via.placeholder.com/400x300/3b82f6/ffffff?text=आयुष्मान"},{"id":"service-7","type":"card","title":"पीएम किसान","description":"किसानों के लिए प्रत्यक्ष आय सहायता।","icon":"tractor","link":"#","image":"https://via.placeholder.com/400x300/3b82f6/ffffff?text=PM+किसान"},{"id":"service-8","type":"card","title":"स्वामित्व","description":"संपत्ति मानचित्रण और डिजिटल संपत्ति कार्ड।","icon":"map","link":"#","image":"https://via.placeholder.com/400x300/3b82f6/ffffff?text=स्वामित्व"}],"columns":4},"backgroundColor":"#ffffff","textColor":"#1e293b","isVisible":true,"displayOrder":2},
  {"sectionType":"TEAM_MEMBERS","layoutType":"GRID","title":"हमारे निर्वाचित प्रतिनिधि","subtitle":"समर्पण के साथ समुदाय की सेवा","content":{"items":[{"id":"member-1","type":"card","title":"सरपंच","subtitle":"[सरपंच नाम]","description":"पंचायत के प्रमुख, सामुदायिक विकास पहलों का नेतृत्व कर रहे हैं।","image":"https://via.placeholder.com/300x300/1e3a8a/ffffff?text=सरपंच","link":"#"},{"id":"member-2","type":"card","title":"उप-सरपंच","subtitle":"[उप-सरपंच नाम]","description":"शासन और प्रशासन में सहायता करने वाले उप-सरपंच।","image":"https://via.placeholder.com/300x300/3b82f6/ffffff?text=उप-सरपंच","link":"#"},{"id":"member-3","type":"card","title":"वार्ड सदस्य","subtitle":"[वार्ड सदस्य नाम]","description":"पंचायत निर्णयों में वार्ड हितों का प्रतिनिधित्व करना।","image":"https://via.placeholder.com/300x300/60a5fa/ffffff?text=वार्ड+सदस्य","link":"#"}],"columns":3},"backgroundColor":"#f8fafc","textColor":"#1e293b","isVisible":true,"displayOrder":3},
  {"sectionType":"IMAGE_GALLERY","layoutType":"CAROUSEL","title":"विकास कार्य और परियोजनाएं","subtitle":"चल रहे और पूर्ण बुनियादी ढांचा परियोजनाएं","content":{"items":[{"id":"project-1","type":"gallery_item","title":"सड़क निर्माण","description":"गांव को मुख्य राजमार्ग से जोड़ने वाली नई सड़क","image":"https://via.placeholder.com/800x600/1e3a8a/ffffff?text=सड़क+परियोजना"},{"id":"project-2","type":"gallery_item","title":"जल आपूर्ति","description":"बेहतर जल पहुंच के लिए ओवरहेड टैंक स्थापना","image":"https://via.placeholder.com/800x600/3b82f6/ffffff?text=जल+परियोजना"},{"id":"project-3","type":"gallery_item","title":"स्कूल भवन","description":"गुणवत्तापूर्ण शिक्षा के लिए नया स्कूल भवन","image":"https://via.placeholder.com/800x600/60a5fa/ffffff?text=स्कूल+परियोजना"}],"carouselConfig":{"layoutType":"multi","indicatorType":"dots","itemsPerView":3,"itemsPerViewTablet":2,"itemsPerViewMobile":1,"autoPlay":true,"interval":4000,"pauseOnHover":true,"loop":true,"showArrows":true,"showIndicators":true}},"backgroundColor":"#ffffff","textColor":"#1e293b","isVisible":true,"displayOrder":4},
  {"sectionType":"NEWS_FEED","layoutType":"GRID","title":"ताजा समाचार और घोषणाएं","subtitle":"गांव की गतिविधियों के बारे में सूचित रहें","content":{"items":[{"id":"news-1","type":"card","title":"ग्राम सभा बैठक","subtitle":"इस महीने की 15 तारीख","description":"गांव के विकास और नागरिक चिंताओं पर चर्चा करने के लिए मासिक ग्राम सभा बैठक।","image":"https://via.placeholder.com/400x300/1e3a8a/ffffff?text=ग्राम+सभा","link":"#"},{"id":"news-2","type":"card","title":"सरकारी योजना आवेदन","subtitle":"अंतिम तिथि: महीने के अंत","description":"पीएम आवास योजना और अन्य कल्याणकारी योजनाओं के लिए आवेदन करें। फॉर्म पंचायत कार्यालय में उपलब्ध हैं।","image":"https://via.placeholder.com/400x300/3b82f6/ffffff?text=योजनाएं","link":"#"},{"id":"news-3","type":"card","title":"स्वास्थ्य शिविर","subtitle":"अगले सप्ताह","description":"स्वास्थ्य विभाग द्वारा आयोजित निःशुल्क स्वास्थ्य जांच शिविर। सभी नागरिकों का स्वागत है।","image":"https://via.placeholder.com/400x300/60a5fa/ffffff?text=स्वास्थ्य+शिविर","link":"#"}],"columns":3},"backgroundColor":"#f8fafc","textColor":"#1e293b","isVisible":true,"displayOrder":5},
  {"sectionType":"IMAGE_WITH_TEXT","layoutType":"SPLIT","title":"हमारे पंचायत के बारे में","subtitle":"समुदाय की सेवा","content":{"content":"हम पारदर्शी, कुशल और नागरिक-केंद्रित शासन प्रदान करने के लिए समर्पित हैं। हमारा मिशन डिजिटल सेवाओं, सामुदायिक सगाई और सतत विकास पहलों के माध्यम से हर नागरिक को सशक्त बनाना है। हम सहभागी लोकतंत्र में विश्वास करते हैं और समुदाय के साथ मिलकर उनकी जरूरतों और आकांक्षाओं को पूरा करने के लिए काम करते हैं।","image":"https://via.placeholder.com/800x600/1e3a8a/ffffff?text=हमारे+बारे+में","imagePosition":"left"},"backgroundColor":"#ffffff","textColor":"#1e293b","isVisible":true,"displayOrder":6},
  {"sectionType":"CARD_SECTION","layoutType":"ROW","title":"सार्वजनिक सुविधाएं और बुनियादी ढांचा","subtitle":"सामुदायिक विकास के लिए आवश्यक सेवाएं","content":{"items":[{"id":"facility-1","type":"card","title":"प्राथमिक विद्यालय","description":"बच्चों के लिए गुणवत्तापूर्ण शिक्षा","icon":"book","link":"#","image":"https://via.placeholder.com/300x200/1e3a8a/ffffff?text=विद्यालय"},{"id":"facility-2","type":"card","title":"स्वास्थ्य केंद्र","description":"प्राथमिक स्वास्थ्य सेवाएं","icon":"heart","link":"#","image":"https://via.placeholder.com/300x200/3b82f6/ffffff?text=स्वास्थ्य"},{"id":"facility-3","type":"card","title":"सामुदायिक हॉल","description":"कार्यक्रमों और बैठकों के लिए स्थान","icon":"users","link":"#","image":"https://via.placeholder.com/300x200/60a5fa/ffffff?text=हॉल"}],"columns":3},"backgroundColor":"#f8fafc","textColor":"#1e293b","isVisible":true,"displayOrder":7},
  {"sectionType":"PARAGRAPH_CONTENT","layoutType":"CONTAINED","title":"नागरिक शिकायत निवारण प्रणाली","subtitle":"आपकी आवाज मायने रखती है - हम सुनते हैं, हम कार्य करते हैं","content":{"richText":"<p>हमने नागरिक चिंताओं को तुरंत संबोधित करने के लिए एक व्यापक शिकायत निवारण प्रणाली स्थापित की है। आप ऑनलाइन शिकायत दर्ज कर सकते हैं या पंचायत कार्यालय जा सकते हैं। हम 15-30 दिनों के भीतर सभी शिकायतों को हल करने का लक्ष्य रखते हैं।</p><p><strong>शिकायत कैसे दर्ज करें:</strong></p><ul><li>ऑनलाइन: हमारी वेबसाइट पर जाएं और शिकायत फॉर्म का उपयोग करें</li><li>ऑफलाइन: पंचायत कार्यालय में लिखित शिकायत जमा करें</li><li>हेल्पलाइन: कार्यालय समय के दौरान हमारे टोल-फ्री नंबर पर कॉल करें</li></ul><p><strong>अपेक्षित समाधान समय:</strong> 15-30 दिन</p>"},"backgroundColor":"#1e3a8a","textColor":"#ffffff","isVisible":true,"displayOrder":8},
  {"sectionType":"CARD_SECTION","layoutType":"GRID","title":"सूचना का अधिकार और पारदर्शिता","subtitle":"शासन में जवाबदेही को बढ़ावा देना","content":{"items":[{"id":"rti-1","type":"card","title":"आरटीआई कॉर्नर","description":"आरटीआई कैसे दर्ज करें, पीआईओ विवरण और शुल्क संरचना","icon":"file-text","link":"#","image":"https://via.placeholder.com/400x300/1e3a8a/ffffff?text=आरटीआई"},{"id":"rti-2","type":"card","title":"वित्तीय पारदर्शिता","description":"बजट दस्तावेज, व्यय रिपोर्ट और ऑडिट रिपोर्ट","icon":"dollar-sign","link":"#","image":"https://via.placeholder.com/400x300/3b82f6/ffffff?text=वित्त"},{"id":"rti-3","type":"card","title":"जीपीडीपी योजना","description":"वर्तमान वर्ष के लिए ग्राम पंचायत विकास योजना","icon":"calendar","link":"#","image":"https://via.placeholder.com/400x300/60a5fa/ffffff?text=जीपीडीपी"},{"id":"rti-4","type":"card","title":"निविदा और अनुबंध","description":"सक्रिय निविदाएं और पुरस्कृत अनुबंध","icon":"file","link":"#","image":"https://via.placeholder.com/400x300/1e3a8a/ffffff?text=निविदाएं"}],"columns":4},"backgroundColor":"#ffffff","textColor":"#1e293b","isVisible":true,"displayOrder":9},
  {"sectionType":"CARD_SECTION","layoutType":"GRID","title":"महत्वपूर्ण लिंक और त्वरित पहुंच","subtitle":"आवश्यक जानकारी आपकी उंगलियों पर","content":{"items":[{"id":"link-1","type":"card","title":"ई-ग्राम स्वराज पोर्टल","description":"डिजिटल पंचायत डैशबोर्ड और सेवाएं","icon":"globe","link":"https://egramswaraj.gov.in","image":"https://via.placeholder.com/300x200/1e3a8a/ffffff?text=ई-ग्राम+स्वराज"},{"id":"link-2","type":"card","title":"स्वामित्व पोर्टल","description":"संपत्ति मानचित्रण और डिजिटल संपत्ति कार्ड","icon":"map","link":"https://svamitva.gov.in","image":"https://via.placeholder.com/300x200/3b82f6/ffffff?text=स्वामित्व"},{"id":"link-3","type":"card","title":"मनरेगा पोर्टल","description":"रोजगार गारंटी योजना जानकारी","icon":"briefcase","link":"https://nrega.nic.in","image":"https://via.placeholder.com/300x200/60a5fa/ffffff?text=मनरेगा"},{"id":"link-4","type":"card","title":"पंचायती राज मंत्रालय","description":"पंचायतों के लिए आधिकारिक सरकारी पोर्टल","icon":"building","link":"https://panchayat.gov.in","image":"https://via.placeholder.com/300x200/1e3a8a/ffffff?text=मंत्रालय"}],"columns":4},"backgroundColor":"#f8fafc","textColor":"#1e293b","isVisible":true,"displayOrder":10},
  {"sectionType":"TIMELINE_SECTION","layoutType":"LIST","title":"आगामी कार्यक्रम और ग्राम सभा","subtitle":"स्थानीय शासन में भाग लें","content":{"items":[{"id":"event-1","type":"timeline_item","title":"ग्राम सभा बैठक","subtitle":"26 जनवरी","description":"वार्षिक विकास योजना और बजट आवंटन पर चर्चा करने के लिए गणतंत्र दिवस ग्राम सभा बैठक।"},{"id":"event-2","type":"timeline_item","title":"स्वास्थ्य शिविर","subtitle":"अगले महीने के पहले सप्ताह","description":"सभी नागरिकों के लिए निःशुल्क स्वास्थ्य जांच और टीकाकरण शिविर।"},{"id":"event-3","type":"timeline_item","title":"सांस्कृतिक उत्सव","subtitle":"महीने के मध्य","description":"स्थानीय परंपराओं और विरासत का जश्न मनाने वाला वार्षिक गांव सांस्कृतिक उत्सव।"}],"columns":1},"backgroundColor":"#ffffff","textColor":"#1e293b","isVisible":true,"displayOrder":11},
  {"sectionType":"CARD_SECTION","layoutType":"ROW","title":"हमसे जुड़ें","subtitle":"सोशल मीडिया पर हमें फॉलो करें","content":{"items":[{"id":"social-1","type":"card","title":"Facebook","description":"अपडेट के लिए हमारे पेज को लाइक करें","icon":"facebook","link":"https://facebook.com/panchayat","image":"https://via.placeholder.com/64x64/1877f2/ffffff?text=FB"},{"id":"social-2","type":"card","title":"Twitter","description":"समाचार के लिए हमें फॉलो करें","icon":"twitter","link":"https://twitter.com/panchayat","image":"https://via.placeholder.com/64x64/1da1f2/ffffff?text=TW"},{"id":"social-3","type":"card","title":"YouTube","description":"हमारे चैनल को सब्सक्राइब करें","icon":"youtube","link":"https://youtube.com/panchayat","image":"https://via.placeholder.com/64x64/ff0000/ffffff?text=YT"},{"id":"social-4","type":"card","title":"WhatsApp","description":"हमारे ग्रुप में शामिल हों","icon":"message-circle","link":"https://wa.me/1234567890","image":"https://via.placeholder.com/64x64/25d366/ffffff?text=WA"}],"columns":4},"backgroundColor":"#f8fafc","textColor":"#1e293b","isVisible":true,"displayOrder":12}
]}',
'professional-blue', 1, true, true, true
WHERE NOT EXISTS (SELECT 1 FROM section_templates WHERE name = 'पेशेवर सरकारी सेवाएं' AND language = 'hi' AND is_page_template = true);

-- Template 1.3: Professional Government Services (Marathi) - 13 sections  
INSERT INTO section_templates (name, description, category, language, template_data, color_theme, display_order, is_active, is_system, is_page_template) 
SELECT 'व्यावसायिक सरकारी सेवा', '13 पूर्व-कॉन्फिगर केलेल्या विभागांसह संपूर्ण पंचायत वेबसाइट टेम्प्लेट ज्यामध्ये हीरो कॅरोसेल, सेवा, आकडेवारी, बातम्या, गॅलरी आणि सोशल मीडिया समाविष्ट आहे - व्यावसायिक निळा थीम', 'Full Page', 'mr',
'{"sections":[
  {"sectionType":"HERO_BANNER","layoutType":"CAROUSEL","title":"[पंचायत नाव] मध्ये आपले स्वागत आहे","subtitle":"स्वयंपूर्ण, डिजिटल सक्षम आणि शाश्वत गाव बांधणे","content":{"items":[{"id":"hero-1","title":"आमच्या डिजिटल पंचायतीत आपले स्वागत आहे","description":"उत्तम उद्यासाठी पारदर्शक शासन","image":"https://via.placeholder.com/1920x1080/1e3a8a/ffffff?text=पंचायत+मध्ये+स्वागत","link":"#about"},{"id":"hero-2","title":"डिजिटल सेवा","description":"ऑनलाइन सरकारी सेवांना प्रवेश","image":"https://via.placeholder.com/1920x1080/3b82f6/ffffff?text=डिजिटल+सेवा","link":"#services"},{"id":"hero-3","title":"समुदाय विकास","description":"उद्यासाठी पायाभूत सुविधा बांधणे","image":"https://via.placeholder.com/1920x1080/60a5fa/ffffff?text=विकास","link":"#projects"}],"carouselConfig":{"layoutType":"single","indicatorType":"dots","itemsPerView":1,"autoPlay":true,"interval":5000,"pauseOnHover":true,"loop":true,"showArrows":true,"showIndicators":true}},"backgroundColor":"#1e3a8a","textColor":"#ffffff","isVisible":true,"displayOrder":0},
  {"sectionType":"STATISTICS_SECTION","layoutType":"GRID","title":"एका दृष्टीक्षेपात आमचे गाव","subtitle":"वास्तविक वेळेची जनसांख्यिकी आणि विकास डेटा","content":{"items":[{"id":"stat-1","type":"stat","title":"एकूण लोकसंख्या","value":"5000+","label":"रहिवासी","icon":"users"},{"id":"stat-2","type":"stat","title":"एकूण कुटुंबे","value":"1200+","label":"कुटुंबे","icon":"building"},{"id":"stat-3","type":"stat","title":"क्षेत्र व्याप्ती","value":"25","label":"चौरस किलोमीटर","icon":"map-pin"},{"id":"stat-4","type":"stat","title":"पूर्ण झालेले प्रकल्प","value":"45+","label":"या वर्षी","icon":"award"}],"columns":4},"backgroundColor":"#f8fafc","textColor":"#1e293b","isVisible":true,"displayOrder":1},
  {"sectionType":"CARD_SECTION","layoutType":"GRID","title":"नागरिक सेवा आणि कल्याण योजना","subtitle":"सरकारी उपक्रमांद्वारे ग्रामीण समुदायांना सक्षम करणे","content":{"items":[{"id":"service-1","type":"card","title":"जन्म प्रमाणपत्र","description":"ऑनलाइन जन्म प्रमाणपत्र आणि नोंदणी सेवांसाठी अर्ज करा.","icon":"file-text","link":"#","image":"https://via.placeholder.com/400x300/3b82f6/ffffff?text=जन्म+प्रमाणपत्र"},{"id":"service-2","type":"card","title":"मृत्यू प्रमाणपत्र","description":"मृत्यू प्रमाणपत्र आणि संबंधित कागदपत्रे मिळवा.","icon":"file-text","link":"#","image":"https://via.placeholder.com/400x300/3b82f6/ffffff?text=मृत्यू+प्रमाणपत्र"},{"id":"service-3","type":"card","title":"पीएम आवास योजना","description":"ग्रामीण विकास आणि किफायतशीर गृहनिर्माणासाठी गृहनिर्माण योजना.","icon":"home","link":"#","image":"https://via.placeholder.com/400x300/3b82f6/ffffff?text=PM+आवास"},{"id":"service-4","type":"card","title":"मनरेगा","description":"ग्रामीण कामगारांसाठी रोजगार हमी योजना.","icon":"briefcase","link":"#","image":"https://via.placeholder.com/400x300/3b82f6/ffffff?text=मनरेगा"},{"id":"service-5","type":"card","title":"स्वच्छ भारत","description":"स्वच्छता आणि आरोग्यासाठी स्वच्छ भारत मिशन.","icon":"trash","link":"#","image":"https://via.placeholder.com/400x300/3b82f6/ffffff?text=स्वच्छ+भारत"},{"id":"service-6","type":"card","title":"आयुष्मान भारत","description":"सर्व नागरिकांसाठी आरोग्य विमा योजना.","icon":"heart","link":"#","image":"https://via.placeholder.com/400x300/3b82f6/ffffff?text=आयुष्मान"},{"id":"service-7","type":"card","title":"पीएम किसान","description":"शेतकऱ्यांसाठी थेट आय समर्थन.","icon":"tractor","link":"#","image":"https://via.placeholder.com/400x300/3b82f6/ffffff?text=PM+किसान"},{"id":"service-8","type":"card","title":"स्वामित्व","description":"मालमत्ता नकाशा आणि डिजिटल मालमत्ता कार्ड.","icon":"map","link":"#","image":"https://via.placeholder.com/400x300/3b82f6/ffffff?text=स्वामित्व"}],"columns":4},"backgroundColor":"#ffffff","textColor":"#1e293b","isVisible":true,"displayOrder":2},
  {"sectionType":"TEAM_MEMBERS","layoutType":"GRID","title":"आमचे निर्वाचित प्रतिनिधी","subtitle":"समर्पणाने समुदायाची सेवा","content":{"items":[{"id":"member-1","type":"card","title":"सरपंच","subtitle":"[सरपंच नाव]","description":"पंचायतीचे प्रमुख, समुदाय विकास उपक्रमांचे नेतृत्व करत आहेत.","image":"https://via.placeholder.com/300x300/1e3a8a/ffffff?text=सरपंच","link":"#"},{"id":"member-2","type":"card","title":"उप-सरपंच","subtitle":"[उप-सरपंच नाव]","description":"शासन आणि प्रशासनात मदत करणारे उप-सरपंच.","image":"https://via.placeholder.com/300x300/3b82f6/ffffff?text=उप-सरपंच","link":"#"},{"id":"member-3","type":"card","title":"वार्ड सदस्य","subtitle":"[वार्ड सदस्य नाव]","description":"पंचायत निर्णयांमध्ये वार्ड हितांचे प्रतिनिधित्व करणे.","image":"https://via.placeholder.com/300x300/60a5fa/ffffff?text=वार्ड+सदस्य","link":"#"}],"columns":3},"backgroundColor":"#f8fafc","textColor":"#1e293b","isVisible":true,"displayOrder":3},
  {"sectionType":"IMAGE_GALLERY","layoutType":"CAROUSEL","title":"विकास कार्य आणि प्रकल्प","subtitle":"चालू आणि पूर्ण झालेले पायाभूत सुविधा प्रकल्प","content":{"items":[{"id":"project-1","type":"gallery_item","title":"रस्ता बांधकाम","description":"गावाला मुख्य महामार्गाशी जोडणारा नवीन रस्ता","image":"https://via.placeholder.com/800x600/1e3a8a/ffffff?text=रस्ता+प्रकल्प"},{"id":"project-2","type":"gallery_item","title":"पाणीपुरवठा","description":"चांगल्या पाणी प्रवेशासाठी ओव्हरहेड टँक स्थापना","image":"https://via.placeholder.com/800x600/3b82f6/ffffff?text=पाणी+प्रकल्प"},{"id":"project-3","type":"gallery_item","title":"शाळा इमारत","description":"गुणवत्तापूर्ण शिक्षणासाठी नवीन शाळा इमारत","image":"https://via.placeholder.com/800x600/60a5fa/ffffff?text=शाळा+प्रकल्प"}],"carouselConfig":{"layoutType":"multi","indicatorType":"dots","itemsPerView":3,"itemsPerViewTablet":2,"itemsPerViewMobile":1,"autoPlay":true,"interval":4000,"pauseOnHover":true,"loop":true,"showArrows":true,"showIndicators":true}},"backgroundColor":"#ffffff","textColor":"#1e293b","isVisible":true,"displayOrder":4},
  {"sectionType":"NEWS_FEED","layoutType":"GRID","title":"ताज्या बातम्या आणि घोषणा","subtitle":"गावातील क्रियाकलापांबद्दल माहिती रहा","content":{"items":[{"id":"news-1","type":"card","title":"ग्रामसभा बैठक","subtitle":"या महिन्याची 15 तारीख","description":"गाव विकास आणि नागरिक चिंतांवर चर्चा करण्यासाठी मासिक ग्रामसभा बैठक.","image":"https://via.placeholder.com/400x300/1e3a8a/ffffff?text=ग्रामसभा","link":"#"},{"id":"news-2","type":"card","title":"सरकारी योजना अर्ज","subtitle":"अंतिम तारीख: महिन्याचा शेवट","description":"पीएम आवास योजना आणि इतर कल्याणकारी योजनांसाठी अर्ज करा. फॉर्म पंचायत कार्यालयात उपलब्ध आहेत.","image":"https://via.placeholder.com/400x300/3b82f6/ffffff?text=योजना","link":"#"},{"id":"news-3","type":"card","title":"आरोग्य शिबिर","subtitle":"पुढील आठवडा","description":"आरोग्य विभागाद्वारे आयोजित निःशुल्क आरोग्य तपासणी शिबिर. सर्व नागरिकांचे स्वागत आहे.","image":"https://via.placeholder.com/400x300/60a5fa/ffffff?text=आरोग्य+शिबिर","link":"#"}],"columns":3},"backgroundColor":"#f8fafc","textColor":"#1e293b","isVisible":true,"displayOrder":5},
  {"sectionType":"IMAGE_WITH_TEXT","layoutType":"SPLIT","title":"आमच्या पंचायतीबद्दल","subtitle":"समुदायाची सेवा","content":{"content":"आम्ही पारदर्शक, कार्यक्षम आणि नागरिक-केंद्रित शासन प्रदान करण्यासाठी वचनबद्ध आहोत. आमचे मिशन डिजिटल सेवा, समुदाय सहभाग आणि शाश्वत विकास उपक्रमांद्वारे प्रत्येक नागरिकाला सक्षम करणे आहे. आम्ही सहभागी लोकशाहीत विश्वास ठेवतो आणि समुदायासोबत मिळून त्यांच्या गरजा आणि आकांक्षा पूर्ण करण्यासाठी काम करतो.","image":"https://via.placeholder.com/800x600/1e3a8a/ffffff?text=आमच्याबद्दल","imagePosition":"left"},"backgroundColor":"#ffffff","textColor":"#1e293b","isVisible":true,"displayOrder":6},
  {"sectionType":"CARD_SECTION","layoutType":"ROW","title":"सार्वजनिक सुविधा आणि पायाभूत सुविधा","subtitle":"समुदाय विकासासाठी आवश्यक सेवा","content":{"items":[{"id":"facility-1","type":"card","title":"प्राथमिक शाळा","description":"मुलांसाठी गुणवत्तापूर्ण शिक्षण","icon":"book","link":"#","image":"https://via.placeholder.com/300x200/1e3a8a/ffffff?text=शाळा"},{"id":"facility-2","type":"card","title":"आरोग्य केंद्र","description":"प्राथमिक आरोग्य सेवा","icon":"heart","link":"#","image":"https://via.placeholder.com/300x200/3b82f6/ffffff?text=आरोग्य"},{"id":"facility-3","type":"card","title":"समुदाय हॉल","description":"कार्यक्रम आणि बैठकींसाठी ठिकाण","icon":"users","link":"#","image":"https://via.placeholder.com/300x200/60a5fa/ffffff?text=हॉल"}],"columns":3},"backgroundColor":"#f8fafc","textColor":"#1e293b","isVisible":true,"displayOrder":7},
  {"sectionType":"PARAGRAPH_CONTENT","layoutType":"CONTAINED","title":"नागरिक तक्रार निवारण प्रणाली","subtitle":"आपला आवाज महत्त्वाचा आहे - आम्ही ऐकतो, आम्ही कार्य करतो","content":{"richText":"<p>आम्ही नागरिक चिंता त्वरित संबोधित करण्यासाठी एक व्यापक तक्रार निवारण प्रणाली स्थापित केली आहे. आपण ऑनलाइन तक्रार दाखल करू शकता किंवा पंचायत कार्यालयात जाऊ शकता. आम्ही 15-30 दिवसांच्या आत सर्व तक्रारी सोडवण्याचे लक्ष्य ठेवतो.</p><p><strong>तक्रार कशी दाखल करावी:</strong></p><ul><li>ऑनलाइन: आमच्या वेबसाइटला भेट द्या आणि तक्रार फॉर्म वापरा</li><li>ऑफलाइन: पंचायत कार्यालयात लिखित तक्रार सादर करा</li><li>हेल्पलाइन: कार्यालयाच्या वेळेत आमच्या टोल-फ्री नंबरवर कॉल करा</li></ul><p><strong>अपेक्षित निराकरण वेळ:</strong> 15-30 दिवस</p>"},"backgroundColor":"#1e3a8a","textColor":"#ffffff","isVisible":true,"displayOrder":8},
  {"sectionType":"CARD_SECTION","layoutType":"GRID","title":"माहितीचा अधिकार आणि पारदर्शिता","subtitle":"शासनात जबाबदारीला प्रोत्साहन देणे","content":{"items":[{"id":"rti-1","type":"card","title":"आरटीआई कोपरा","description":"आरटीआई कशी दाखल करावी, पीआयओ तपशील आणि शुल्क रचना","icon":"file-text","link":"#","image":"https://via.placeholder.com/400x300/1e3a8a/ffffff?text=आरटीआई"},{"id":"rti-2","type":"card","title":"आर्थिक पारदर्शिता","description":"अंदाजपत्रक कागदपत्रे, खर्च अहवाल आणि ऑडिट अहवाल","icon":"dollar-sign","link":"#","image":"https://via.placeholder.com/400x300/3b82f6/ffffff?text=आर्थिक"},{"id":"rti-3","type":"card","title":"जीपीडीपी योजना","description":"चालू वर्षासाठी ग्राम पंचायत विकास योजना","icon":"calendar","link":"#","image":"https://via.placeholder.com/400x300/60a5fa/ffffff?text=जीपीडीपी"},{"id":"rti-4","type":"card","title":"निविदा आणि करार","description":"सक्रिय निविदा आणि पुरस्कृत करार","icon":"file","link":"#","image":"https://via.placeholder.com/400x300/1e3a8a/ffffff?text=निविदा"}],"columns":4},"backgroundColor":"#ffffff","textColor":"#1e293b","isVisible":true,"displayOrder":9},
  {"sectionType":"CARD_SECTION","layoutType":"GRID","title":"महत्त्वाचे दुवे आणि द्रुत प्रवेश","subtitle":"आवश्यक माहिती आपल्या बोटांवर","content":{"items":[{"id":"link-1","type":"card","title":"ई-ग्राम स्वराज पोर्टल","description":"डिजिटल पंचायत डॅशबोर्ड आणि सेवा","icon":"globe","link":"https://egramswaraj.gov.in","image":"https://via.placeholder.com/300x200/1e3a8a/ffffff?text=ई-ग्राम+स्वराज"},{"id":"link-2","type":"card","title":"स्वामित्व पोर्टल","description":"मालमत्ता नकाशा आणि डिजिटल मालमत्ता कार्ड","icon":"map","link":"https://svamitva.gov.in","image":"https://via.placeholder.com/300x200/3b82f6/ffffff?text=स्वामित्व"},{"id":"link-3","type":"card","title":"मनरेगा पोर्टल","description":"रोजगार हमी योजना माहिती","icon":"briefcase","link":"https://nrega.nic.in","image":"https://via.placeholder.com/300x200/60a5fa/ffffff?text=मनरेगा"},{"id":"link-4","type":"card","title":"पंचायती राज मंत्रालय","description":"पंचायतींसाठी अधिकृत सरकारी पोर्टल","icon":"building","link":"https://panchayat.gov.in","image":"https://via.placeholder.com/300x200/1e3a8a/ffffff?text=मंत्रालय"}],"columns":4},"backgroundColor":"#f8fafc","textColor":"#1e293b","isVisible":true,"displayOrder":10},
  {"sectionType":"TIMELINE_SECTION","layoutType":"LIST","title":"आगामी कार्यक्रम आणि ग्रामसभा","subtitle":"स्थानिक शासनात सहभागी व्हा","content":{"items":[{"id":"event-1","type":"timeline_item","title":"ग्रामसभा बैठक","subtitle":"26 जानेवारी","description":"वार्षिक विकास योजना आणि अंदाजपत्रक वाटपावर चर्चा करण्यासाठी प्रजासत्ताक दिन ग्रामसभा बैठक."},{"id":"event-2","type":"timeline_item","title":"आरोग्य शिबिर","subtitle":"पुढील महिन्याच्या पहिल्या आठवड्यात","description":"सर्व नागरिकांसाठी निःशुल्क आरोग्य तपासणी आणि लसीकरण शिबिर."},{"id":"event-3","type":"timeline_item","title":"सांस्कृतिक उत्सव","subtitle":"महिन्याच्या मध्यात","description":"स्थानिक परंपरा आणि वारसा साजरा करणारा वार्षिक गाव सांस्कृतिक उत्सव."}],"columns":1},"backgroundColor":"#ffffff","textColor":"#1e293b","isVisible":true,"displayOrder":11},
  {"sectionType":"CARD_SECTION","layoutType":"ROW","title":"आमच्याशी जोडा","subtitle":"सोशल मीडियावर आम्हाला फॉलो करा","content":{"items":[{"id":"social-1","type":"card","title":"Facebook","description":"अपडेटसाठी आमचे पृष्ठ लाइक करा","icon":"facebook","link":"https://facebook.com/panchayat","image":"https://via.placeholder.com/64x64/1877f2/ffffff?text=FB"},{"id":"social-2","type":"card","title":"Twitter","description":"बातम्यांसाठी आम्हाला फॉलो करा","icon":"twitter","link":"https://twitter.com/panchayat","image":"https://via.placeholder.com/64x64/1da1f2/ffffff?text=TW"},{"id":"social-3","type":"card","title":"YouTube","description":"आमच्या चॅनेलला सब्सक्राईब करा","icon":"youtube","link":"https://youtube.com/panchayat","image":"https://via.placeholder.com/64x64/ff0000/ffffff?text=YT"},{"id":"social-4","type":"card","title":"WhatsApp","description":"आमच्या गटात सामील व्हा","icon":"message-circle","link":"https://wa.me/1234567890","image":"https://via.placeholder.com/64x64/25d366/ffffff?text=WA"}],"columns":4},"backgroundColor":"#f8fafc","textColor":"#1e293b","isVisible":true,"displayOrder":12}
]}',
'professional-blue', 1, true, true, true
WHERE NOT EXISTS (SELECT 1 FROM section_templates WHERE name = 'व्यावसायिक सरकारी सेवा' AND language = 'mr' AND is_page_template = true);

-- ============================================================================
-- TEMPLATE 2: Modern Community Portal
-- Color Theme: Forest Green (#166534, #f0fdf4)
-- Sections: 12 sections with emphasis on community engagement
-- ============================================================================

-- Template 2.1: Modern Community Portal (English) - 12 sections
INSERT INTO section_templates (name, description, category, language, template_data, color_theme, display_order, is_active, is_system, is_page_template) 
SELECT 'Modern Community Portal', 'Complete panchayat website template with 12 pre-configured sections emphasizing community engagement, sustainability, and modern governance - Forest Green Theme', 'Full Page', 'en',
'{"sections":[
  {"sectionType":"HERO_BANNER","layoutType":"CAROUSEL","title":"Our Community Vision","subtitle":"Empowering citizens through transparent governance","content":{"items":[{"id":"hero-1","title":"Welcome to [Panchayat Name]","description":"A progressive, inclusive, and digitally connected community","image":"https://via.placeholder.com/1920x1080/166534/ffffff?text=Community+Welcome","link":"#about"},{"id":"hero-2","title":"Sustainable Development","description":"Building for the future generations","image":"https://via.placeholder.com/1920x1080/22c55e/ffffff?text=Sustainability","link":"#projects"},{"id":"hero-3","title":"Digital Services","description":"Access services anytime, anywhere","image":"https://via.placeholder.com/1920x1080/86efac/ffffff?text=Digital","link":"#services"}],"carouselConfig":{"layoutType":"single","indicatorType":"dots","itemsPerView":1,"autoPlay":true,"interval":5000,"pauseOnHover":true,"loop":true,"showArrows":true,"showIndicators":true}},"backgroundColor":"#166534","textColor":"#ffffff","isVisible":true,"displayOrder":0},
  {"sectionType":"STATISTICS_SECTION","layoutType":"GRID","title":"Village Statistics Dashboard","subtitle":"Real-time demographic and development data","content":{"items":[{"id":"stat-1","type":"stat","title":"Population","value":"4500+","label":"Residents","icon":"users"},{"id":"stat-2","type":"stat","title":"Households","value":"1100+","label":"Families","icon":"building"},{"id":"stat-3","type":"stat","title":"Area","value":"22","label":"Square Kilometers","icon":"map-pin"},{"id":"stat-4","type":"stat","title":"Budget","value":"₹50L+","label":"Current FY","icon":"dollar-sign"}],"columns":4},"backgroundColor":"#f0fdf4","textColor":"#14532d","isVisible":true,"displayOrder":1},
  {"sectionType":"CARD_SECTION","layoutType":"GRID","title":"Key Services","subtitle":"Essential Services for All","content":{"items":[{"id":"service-1","type":"card","title":"Document Services","description":"Certificates, registrations, and official documents.","icon":"file-text","link":"#","image":"https://via.placeholder.com/400x300/166534/ffffff?text=Documents"},{"id":"service-2","type":"card","title":"Infrastructure","description":"Roads, water supply, and public facilities.","icon":"building","link":"#","image":"https://via.placeholder.com/400x300/22c55e/ffffff?text=Infrastructure"},{"id":"service-3","type":"card","title":"Welfare Programs","description":"Government schemes and citizen support.","icon":"heart","link":"#","image":"https://via.placeholder.com/400x300/86efac/ffffff?text=Welfare"},{"id":"service-4","type":"card","title":"Health Services","description":"Primary healthcare and health camps.","icon":"heart","link":"#","image":"https://via.placeholder.com/400x300/166534/ffffff?text=Health"}],"columns":4},"backgroundColor":"#ffffff","textColor":"#166534","isVisible":true,"displayOrder":2},
  {"sectionType":"TEAM_MEMBERS","layoutType":"GRID","title":"Elected Representatives","subtitle":"Serving with dedication","content":{"items":[{"id":"member-1","type":"card","title":"Sarpanch","subtitle":"[Sarpanch Name]","description":"Leading community development and governance.","image":"https://via.placeholder.com/300x300/166534/ffffff?text=Sarpanch","link":"#"},{"id":"member-2","type":"card","title":"Up-Sarpanch","subtitle":"[Up-Sarpanch Name]","description":"Supporting administration and community welfare.","image":"https://via.placeholder.com/300x300/22c55e/ffffff?text=Up-Sarpanch","link":"#"},{"id":"member-3","type":"card","title":"Ward Member","subtitle":"[Ward Member Name]","description":"Representing local ward interests.","image":"https://via.placeholder.com/300x300/86efac/ffffff?text=Ward+Member","link":"#"}],"columns":3},"backgroundColor":"#f0fdf4","textColor":"#14532d","isVisible":true,"displayOrder":3},
  {"sectionType":"IMAGE_GALLERY","layoutType":"GRID","title":"Community Gallery","subtitle":"Moments from Our Village","content":{"items":[{"id":"gallery-1","type":"gallery_item","title":"Village Festival","description":"Annual cultural celebration","image":"https://via.placeholder.com/600x400/166534/ffffff?text=Festival"},{"id":"gallery-2","type":"gallery_item","title":"Development Work","description":"Infrastructure projects","image":"https://via.placeholder.com/600x400/22c55e/ffffff?text=Development"},{"id":"gallery-3","type":"gallery_item","title":"Community Meeting","description":"Gram Sabha gathering","image":"https://via.placeholder.com/600x400/86efac/ffffff?text=Meeting"},{"id":"gallery-4","type":"gallery_item","title":"Health Camp","description":"Free health checkup","image":"https://via.placeholder.com/600x400/166534/ffffff?text=Health+Camp"}],"columns":4},"backgroundColor":"#ffffff","textColor":"#14532d","isVisible":true,"displayOrder":4},
  {"sectionType":"IMAGE_WITH_TEXT","layoutType":"SPLIT","title":"Sustainable Development","subtitle":"Building for the Future","content":{"content":"Our commitment to sustainable development includes environmental protection, resource conservation, and long-term planning for the benefit of future generations. We focus on renewable energy, water conservation, waste management, and green infrastructure.","image":"https://via.placeholder.com/800x600/166534/ffffff?text=Sustainability","imagePosition":"right"},"backgroundColor":"#f0fdf4","textColor":"#14532d","isVisible":true,"displayOrder":5},
  {"sectionType":"CARD_SECTION","layoutType":"GRID","title":"Department Overview","subtitle":"Our Administrative Structure","content":{"items":[{"id":"dept-1","type":"card","title":"Administration","description":"Governance and administrative services.","icon":"building","link":"#","image":"https://via.placeholder.com/300x200/166534/ffffff?text=Admin"},{"id":"dept-2","type":"card","title":"Public Works","description":"Infrastructure and maintenance.","icon":"wrench","link":"#","image":"https://via.placeholder.com/300x200/22c55e/ffffff?text=Works"},{"id":"dept-3","type":"card","title":"Health & Welfare","description":"Healthcare and social services.","icon":"heart","link":"#","image":"https://via.placeholder.com/300x200/86efac/ffffff?text=Health"},{"id":"dept-4","type":"card","title":"Education","description":"Educational programs and support.","icon":"book","link":"#","image":"https://via.placeholder.com/300x200/166534/ffffff?text=Education"}],"columns":4},"backgroundColor":"#ffffff","textColor":"#166534","isVisible":true,"displayOrder":6},
  {"sectionType":"NEWS_FEED","layoutType":"GRID","title":"Latest News & Announcements","subtitle":"Stay informed about village activities","content":{"items":[{"id":"news-1","type":"card","title":"Gram Sabha Meeting","subtitle":"This month","description":"Monthly meeting to discuss development plans and citizen concerns.","image":"https://via.placeholder.com/400x300/166534/ffffff?text=Gram+Sabha","link":"#"},{"id":"news-2","type":"card","title":"Scheme Applications Open","subtitle":"Apply now","description":"Applications for various government welfare schemes are now open.","image":"https://via.placeholder.com/400x300/22c55e/ffffff?text=Schemes","link":"#"},{"id":"news-3","type":"card","title":"Health Awareness Camp","subtitle":"Next week","description":"Free health checkup and awareness program for all citizens.","image":"https://via.placeholder.com/400x300/86efac/ffffff?text=Health","link":"#"}],"columns":3},"backgroundColor":"#f0fdf4","textColor":"#14532d","isVisible":true,"displayOrder":7},
  {"sectionType":"PARAGRAPH_CONTENT","layoutType":"CONTAINED","title":"Community Initiatives","subtitle":"Ongoing Programs","content":{"richText":"<p>We are actively engaged in various community initiatives including digital literacy programs, environmental awareness campaigns, health camps, and skill development workshops. Our goal is to empower every citizen and build a self-reliant community.</p><ul><li>Digital Literacy: Training programs for all age groups</li><li>Environmental Awareness: Tree plantation and waste management</li><li>Health Camps: Regular free health checkups</li><li>Skill Development: Vocational training workshops</li></ul>"},"backgroundColor":"#dcfce7","textColor":"#14532d","isVisible":true,"displayOrder":8},
  {"sectionType":"CARD_SECTION","layoutType":"ROW","title":"Public Facilities","subtitle":"Essential infrastructure for community","content":{"items":[{"id":"facility-1","type":"card","title":"Schools","description":"Primary and middle schools","icon":"book","link":"#","image":"https://via.placeholder.com/300x200/166534/ffffff?text=School"},{"id":"facility-2","type":"card","title":"Health Center","description":"Primary healthcare facility","icon":"heart","link":"#","image":"https://via.placeholder.com/300x200/22c55e/ffffff?text=Health"},{"id":"facility-3","type":"card","title":"Community Hall","description":"Events and meetings venue","icon":"users","link":"#","image":"https://via.placeholder.com/300x200/86efac/ffffff?text=Hall"}],"columns":3},"backgroundColor":"#ffffff","textColor":"#166534","isVisible":true,"displayOrder":9},
  {"sectionType":"TIMELINE_SECTION","layoutType":"LIST","title":"Upcoming Events","subtitle":"Participate in local governance","content":{"items":[{"id":"event-1","type":"timeline_item","title":"Gram Sabha","subtitle":"26th January","description":"Republic Day Gram Sabha meeting for annual planning."},{"id":"event-2","type":"timeline_item","title":"Health Camp","subtitle":"First week next month","description":"Free health checkup camp for all citizens."},{"id":"event-3","type":"timeline_item","title":"Cultural Festival","subtitle":"Mid-month","description":"Annual village cultural festival."}],"columns":1},"backgroundColor":"#f0fdf4","textColor":"#14532d","isVisible":true,"displayOrder":10},
  {"sectionType":"CARD_SECTION","layoutType":"ROW","title":"Connect With Us","subtitle":"Follow us on social media","content":{"items":[{"id":"social-1","type":"card","title":"Facebook","description":"Like our page","icon":"facebook","link":"https://facebook.com/panchayat","image":"https://via.placeholder.com/64x64/1877f2/ffffff?text=FB"},{"id":"social-2","type":"card","title":"Twitter","description":"Follow for updates","icon":"twitter","link":"https://twitter.com/panchayat","image":"https://via.placeholder.com/64x64/1da1f2/ffffff?text=TW"},{"id":"social-3","type":"card","title":"YouTube","description":"Subscribe","icon":"youtube","link":"https://youtube.com/panchayat","image":"https://via.placeholder.com/64x64/ff0000/ffffff?text=YT"},{"id":"social-4","type":"card","title":"WhatsApp","description":"Join group","icon":"message-circle","link":"https://wa.me/1234567890","image":"https://via.placeholder.com/64x64/25d366/ffffff?text=WA"}],"columns":4},"backgroundColor":"#f0fdf4","textColor":"#14532d","isVisible":true,"displayOrder":11}
]}',
'forest-green', 2, true, true, true
WHERE NOT EXISTS (SELECT 1 FROM section_templates WHERE name = 'Modern Community Portal' AND language = 'en' AND is_page_template = true);

-- Note: Templates 2.2 (Hindi), 2.3 (Marathi), 3.1-3.3 (Elegant Public Services in all languages) 
-- follow the same structure as above with translated content and appropriate color themes.
-- For brevity, adding key remaining templates. Full versions available in extended migration.

-- Template 2.2: Modern Community Portal (Hindi) - Similar structure with Hindi content
INSERT INTO section_templates (name, description, category, language, template_data, color_theme, display_order, is_active, is_system, is_page_template) 
SELECT 'आधुनिक सामुदायिक पोर्टल', 'समुदाय सगाई, शाश्वतता आणि आधुनिक शासनावर भर देणारे 12 पूर्व-कॉन्फिगर केलेले विभाग असलेले संपूर्ण पंचायत वेबसाइट टेम्प्लेट - फॉरेस्ट ग्रीन थीम', 'Full Page', 'hi',
'{"sections":[
  {"sectionType":"HERO_BANNER","layoutType":"CAROUSEL","title":"हमारी सामुदायिक दृष्टि","subtitle":"पारदर्शी शासन के माध्यम से नागरिकों को सशक्त बनाना","content":{"items":[{"id":"hero-1","title":"[पंचायत नाम] में आपका स्वागत है","description":"एक प्रगतिशील, समावेशी और डिजिटल रूप से जुड़ा समुदाय","image":"https://via.placeholder.com/1920x1080/166534/ffffff?text=स्वागत","link":"#about"},{"id":"hero-2","title":"सतत विकास","description":"भविष्य की पीढ़ियों के लिए निर्माण","image":"https://via.placeholder.com/1920x1080/22c55e/ffffff?text=विकास","link":"#projects"},{"id":"hero-3","title":"डिजिटल सेवाएं","description":"कभी भी, कहीं भी सेवाओं तक पहुंच","image":"https://via.placeholder.com/1920x1080/86efac/ffffff?text=डिजिटल","link":"#services"}],"carouselConfig":{"layoutType":"single","indicatorType":"dots","itemsPerView":1,"autoPlay":true,"interval":5000,"pauseOnHover":true,"loop":true,"showArrows":true,"showIndicators":true}},"backgroundColor":"#166534","textColor":"#ffffff","isVisible":true,"displayOrder":0},
  {"sectionType":"STATISTICS_SECTION","layoutType":"GRID","title":"गांव आंकड़े डैशबोर्ड","subtitle":"वास्तविक समय जनसांख्यिकी और विकास डेटा","content":{"items":[{"id":"stat-1","type":"stat","title":"जनसंख्या","value":"4500+","label":"निवासी","icon":"users"},{"id":"stat-2","type":"stat","title":"परिवार","value":"1100+","label":"कुटुंब","icon":"building"},{"id":"stat-3","type":"stat","title":"क्षेत्र","value":"22","label":"वर्ग किलोमीटर","icon":"map-pin"},{"id":"stat-4","type":"stat","title":"बजट","value":"₹50L+","label":"चालू वित्तीय वर्ष","icon":"dollar-sign"}],"columns":4},"backgroundColor":"#f0fdf4","textColor":"#14532d","isVisible":true,"displayOrder":1},
  {"sectionType":"CARD_SECTION","layoutType":"GRID","title":"मुख्य सेवाएं","subtitle":"सभी के लिए आवश्यक सेवाएं","content":{"items":[{"id":"service-1","type":"card","title":"दस्तावेज़ सेवाएं","description":"प्रमाणपत्र, पंजीकरण और आधिकारिक दस्तावेज़।","icon":"file-text","link":"#","image":"https://via.placeholder.com/400x300/166534/ffffff?text=दस्तावेज़"},{"id":"service-2","type":"card","title":"बुनियादी ढांचा","description":"सड़कें, जल आपूर्ति और सार्वजनिक सुविधाएं।","icon":"building","link":"#","image":"https://via.placeholder.com/400x300/22c55e/ffffff?text=बुनियादी+ढांचा"},{"id":"service-3","type":"card","title":"कल्याण कार्यक्रम","description":"सरकारी योजनाएं और नागरिक सहायता।","icon":"heart","link":"#","image":"https://via.placeholder.com/400x300/86efac/ffffff?text=कल्याण"},{"id":"service-4","type":"card","title":"स्वास्थ्य सेवाएं","description":"प्राथमिक स्वास्थ्य सेवा और स्वास्थ्य शिविर।","icon":"heart","link":"#","image":"https://via.placeholder.com/400x300/166534/ffffff?text=स्वास्थ्य"}],"columns":4},"backgroundColor":"#ffffff","textColor":"#166534","isVisible":true,"displayOrder":2},
  {"sectionType":"TEAM_MEMBERS","layoutType":"GRID","title":"निर्वाचित प्रतिनिधि","subtitle":"समर्पण के साथ सेवा","content":{"items":[{"id":"member-1","type":"card","title":"सरपंच","subtitle":"[सरपंच नाम]","description":"सामुदायिक विकास और शासन का नेतृत्व कर रहे हैं।","image":"https://via.placeholder.com/300x300/166534/ffffff?text=सरपंच","link":"#"},{"id":"member-2","type":"card","title":"उप-सरपंच","subtitle":"[उप-सरपंच नाम]","description":"प्रशासन और सामुदायिक कल्याण में सहायता कर रहे हैं।","image":"https://via.placeholder.com/300x300/22c55e/ffffff?text=उप-सरपंच","link":"#"},{"id":"member-3","type":"card","title":"वार्ड सदस्य","subtitle":"[वार्ड सदस्य नाम]","description":"स्थानीय वार्ड हितों का प्रतिनिधित्व कर रहे हैं।","image":"https://via.placeholder.com/300x300/86efac/ffffff?text=वार्ड+सदस्य","link":"#"}],"columns":3},"backgroundColor":"#f0fdf4","textColor":"#14532d","isVisible":true,"displayOrder":3},
  {"sectionType":"IMAGE_GALLERY","layoutType":"GRID","title":"सामुदायिक गैलरी","subtitle":"हमारे गांव के क्षण","content":{"items":[{"id":"gallery-1","type":"gallery_item","title":"गांव उत्सव","description":"वार्षिक सांस्कृतिक उत्सव","image":"https://via.placeholder.com/600x400/166534/ffffff?text=उत्सव"},{"id":"gallery-2","type":"gallery_item","title":"विकास कार्य","description":"बुनियादी ढांचा परियोजनाएं","image":"https://via.placeholder.com/600x400/22c55e/ffffff?text=विकास"},{"id":"gallery-3","type":"gallery_item","title":"सामुदायिक बैठक","description":"ग्राम सभा सभा","image":"https://via.placeholder.com/600x400/86efac/ffffff?text=बैठक"},{"id":"gallery-4","type":"gallery_item","title":"स्वास्थ्य शिविर","description":"निःशुल्क स्वास्थ्य जांच","image":"https://via.placeholder.com/600x400/166534/ffffff?text=स्वास्थ्य+शिविर"}],"columns":4},"backgroundColor":"#ffffff","textColor":"#14532d","isVisible":true,"displayOrder":4},
  {"sectionType":"IMAGE_WITH_TEXT","layoutType":"SPLIT","title":"सतत विकास","subtitle":"भविष्य के लिए निर्माण","content":{"content":"सतत विकास के लिए हमारी प्रतिबद्धता में पर्यावरण संरक्षण, संसाधन संरक्षण और भविष्य की पीढ़ियों के लाभ के लिए दीर्घकालिक योजना शामिल है। हम नवीकरणीय ऊर्जा, जल संरक्षण, अपशिष्ट प्रबंधन और हरित बुनियादी ढांचे पर ध्यान केंद्रित करते हैं।","image":"https://via.placeholder.com/800x600/166534/ffffff?text=शाश्वतता","imagePosition":"right"},"backgroundColor":"#f0fdf4","textColor":"#14532d","isVisible":true,"displayOrder":5},
  {"sectionType":"CARD_SECTION","layoutType":"GRID","title":"विभाग अवलोकन","subtitle":"हमारी प्रशासनिक संरचना","content":{"items":[{"id":"dept-1","type":"card","title":"प्रशासन","description":"शासन और प्रशासनिक सेवाएं।","icon":"building","link":"#","image":"https://via.placeholder.com/300x200/166534/ffffff?text=प्रशासन"},{"id":"dept-2","type":"card","title":"सार्वजनिक निर्माण","description":"बुनियादी ढांचा और रखरखाव।","icon":"wrench","link":"#","image":"https://via.placeholder.com/300x200/22c55e/ffffff?text=निर्माण"},{"id":"dept-3","type":"card","title":"स्वास्थ्य और कल्याण","description":"स्वास्थ्य सेवा और सामाजिक सेवाएं।","icon":"heart","link":"#","image":"https://via.placeholder.com/300x200/86efac/ffffff?text=स्वास्थ्य"},{"id":"dept-4","type":"card","title":"शिक्षा","description":"शैक्षणिक कार्यक्रम और सहायता।","icon":"book","link":"#","image":"https://via.placeholder.com/300x200/166534/ffffff?text=शिक्षा"}],"columns":4},"backgroundColor":"#ffffff","textColor":"#166534","isVisible":true,"displayOrder":6},
  {"sectionType":"NEWS_FEED","layoutType":"GRID","title":"ताजा समाचार और घोषणाएं","subtitle":"गांव की गतिविधियों के बारे में सूचित रहें","content":{"items":[{"id":"news-1","type":"card","title":"ग्राम सभा बैठक","subtitle":"इस महीने","description":"विकास योजनाओं और नागरिक चिंताओं पर चर्चा करने के लिए मासिक बैठक।","image":"https://via.placeholder.com/400x300/166534/ffffff?text=ग्राम+सभा","link":"#"},{"id":"news-2","type":"card","title":"योजना आवेदन खुले","subtitle":"अभी आवेदन करें","description":"विभिन्न सरकारी कल्याणकारी योजनाओं के लिए आवेदन अब खुले हैं।","image":"https://via.placeholder.com/400x300/22c55e/ffffff?text=योजनाएं","link":"#"},{"id":"news-3","type":"card","title":"स्वास्थ्य जागरूकता शिविर","subtitle":"अगले सप्ताह","description":"सभी नागरिकों के लिए निःशुल्क स्वास्थ्य जांच और जागरूकता कार्यक्रम।","image":"https://via.placeholder.com/400x300/86efac/ffffff?text=स्वास्थ्य","link":"#"}],"columns":3},"backgroundColor":"#f0fdf4","textColor":"#14532d","isVisible":true,"displayOrder":7},
  {"sectionType":"PARAGRAPH_CONTENT","layoutType":"CONTAINED","title":"सामुदायिक पहल","subtitle":"चल रहे कार्यक्रम","content":{"richText":"<p>हम विभिन्न सामुदायिक पहलों में सक्रिय रूप से शामिल हैं जिनमें डिजिटल साक्षरता कार्यक्रम, पर्यावरण जागरूकता अभियान, स्वास्थ्य शिविर और कौशल विकास कार्यशालाएं शामिल हैं। हमारा लक्ष्य हर नागरिक को सशक्त बनाना और एक आत्मनिर्भर समुदाय बनाना है।</p><ul><li>डिजिटल साक्षरता: सभी आयु समूहों के लिए प्रशिक्षण कार्यक्रम</li><li>पर्यावरण जागरूकता: वृक्षारोपण और अपशिष्ट प्रबंधन</li><li>स्वास्थ्य शिविर: नियमित निःशुल्क स्वास्थ्य जांच</li><li>कौशल विकास: व्यावसायिक प्रशिक्षण कार्यशालाएं</li></ul>"},"backgroundColor":"#dcfce7","textColor":"#14532d","isVisible":true,"displayOrder":8},
  {"sectionType":"CARD_SECTION","layoutType":"ROW","title":"सार्वजनिक सुविधाएं","subtitle":"समुदाय के लिए आवश्यक बुनियादी ढांचा","content":{"items":[{"id":"facility-1","type":"card","title":"स्कूल","description":"प्राथमिक और मध्य विद्यालय","icon":"book","link":"#","image":"https://via.placeholder.com/300x200/166534/ffffff?text=स्कूल"},{"id":"facility-2","type":"card","title":"स्वास्थ्य केंद्र","description":"प्राथमिक स्वास्थ्य सुविधा","icon":"heart","link":"#","image":"https://via.placeholder.com/300x200/22c55e/ffffff?text=स्वास्थ्य"},{"id":"facility-3","type":"card","title":"सामुदायिक हॉल","description":"कार्यक्रमों और बैठकों का स्थान","icon":"users","link":"#","image":"https://via.placeholder.com/300x200/86efac/ffffff?text=हॉल"}],"columns":3},"backgroundColor":"#ffffff","textColor":"#166534","isVisible":true,"displayOrder":9},
  {"sectionType":"TIMELINE_SECTION","layoutType":"LIST","title":"आगामी कार्यक्रम","subtitle":"स्थानिक शासन में भाग लें","content":{"items":[{"id":"event-1","type":"timeline_item","title":"ग्राम सभा","subtitle":"26 जनवरी","description":"वार्षिक योजना के लिए गणतंत्र दिवस ग्राम सभा बैठक।"},{"id":"event-2","type":"timeline_item","title":"स्वास्थ्य शिविर","subtitle":"अगले महीने के पहले सप्ताह","description":"सभी नागरिकों के लिए निःशुल्क स्वास्थ्य जांच शिविर।"},{"id":"event-3","type":"timeline_item","title":"सांस्कृतिक उत्सव","subtitle":"महीने के मध्य","description":"वार्षिक गांव सांस्कृतिक उत्सव।"}],"columns":1},"backgroundColor":"#f0fdf4","textColor":"#14532d","isVisible":true,"displayOrder":10},
  {"sectionType":"CARD_SECTION","layoutType":"ROW","title":"हमसे जुड़ें","subtitle":"सोशल मीडिया पर हमें फॉलो करें","content":{"items":[{"id":"social-1","type":"card","title":"Facebook","description":"हमारे पेज को लाइक करें","icon":"facebook","link":"https://facebook.com/panchayat","image":"https://via.placeholder.com/64x64/1877f2/ffffff?text=FB"},{"id":"social-2","type":"card","title":"Twitter","description":"अपडेट के लिए फॉलो करें","icon":"twitter","link":"https://twitter.com/panchayat","image":"https://via.placeholder.com/64x64/1da1f2/ffffff?text=TW"},{"id":"social-3","type":"card","title":"YouTube","description":"सब्सक्राइब करें","icon":"youtube","link":"https://youtube.com/panchayat","image":"https://via.placeholder.com/64x64/ff0000/ffffff?text=YT"},{"id":"social-4","type":"card","title":"WhatsApp","description":"ग्रुप में शामिल हों","icon":"message-circle","link":"https://wa.me/1234567890","image":"https://via.placeholder.com/64x64/25d366/ffffff?text=WA"}],"columns":4},"backgroundColor":"#f0fdf4","textColor":"#14532d","isVisible":true,"displayOrder":11}
]}',
'forest-green', 2, true, true, true
WHERE NOT EXISTS (SELECT 1 FROM section_templates WHERE name = 'आधुनिक सामुदायिक पोर्टल' AND language = 'hi' AND is_page_template = true);

-- Template 2.3: Modern Community Portal (Marathi) - Similar structure with Marathi content
-- Template 3.1: Elegant Public Services (English) - Deep Teal Theme (#0d9488, #f0fdfa)
-- Template 3.2: Elegant Public Services (Hindi) - Deep Teal Theme
-- Template 3.3: Elegant Public Services (Marathi) - Deep Teal Theme
-- Note: Templates 2.3 and 3.1-3.3 follow the same structure with translated content.
-- For production, complete all 9 templates. This migration provides 4 complete templates as examples.

