-- V7: Add Compact Marathi Templates (3-5 sections, no hero)
-- This migration creates 4 compact Marathi templates with fewer sections
-- Each template focuses on essential information without hero banners

-- Template 1: Compact Services Template (Marathi) - 4 sections
INSERT INTO section_templates (name, description, category, language, template_data, color_theme, display_order, is_active, is_system, is_page_template) 
SELECT 'संक्षिप्त सेवा टेम्प्लेट', '4 पूर्व-कॉन्फिगर केलेल्या विभागांसह संक्षिप्त पंचायत वेबसाइट टेम्प्लेट - आकडेवारी, सेवा, टीम आणि बातम्या', 'Full Page', 'mr',
'{"sections":[
  {"sectionType":"STATISTICS_SECTION","layoutType":"GRID","title":"गावाची माहिती","subtitle":"एका दृष्टीक्षेपात आमचे गाव","content":{"items":[{"id":"stat-1","type":"stat","title":"एकूण लोकसंख्या","value":"5000+","label":"रहिवासी","icon":"users"},{"id":"stat-2","type":"stat","title":"एकूण कुटुंबे","value":"1200+","label":"कुटुंबे","icon":"building"},{"id":"stat-3","type":"stat","title":"क्षेत्र व्याप्ती","value":"25","label":"चौरस किमी","icon":"map-pin"},{"id":"stat-4","type":"stat","title":"पूर्ण प्रकल्प","value":"45+","label":"या वर्षी","icon":"award"}],"columns":4},"backgroundColor":"#f8fafc","textColor":"#1e293b","isVisible":true,"displayOrder":0},
  {"sectionType":"CARD_SECTION","layoutType":"GRID","title":"नागरिक सेवा आणि योजना","subtitle":"सरकारी योजना आणि सेवा","content":{"items":[{"id":"service-1","type":"card","title":"जन्म प्रमाणपत्र","description":"ऑनलाइन जन्म प्रमाणपत्र आणि नोंदणी सेवा","icon":"file-text","link":"#","image":"https://via.placeholder.com/400x300/3b82f6/ffffff?text=जन्म+प्रमाणपत्र"},{"id":"service-2","type":"card","title":"पीएम आवास योजना","description":"ग्रामीण विकास आणि किफायतशीर गृहनिर्माण","icon":"home","link":"#","image":"https://via.placeholder.com/400x300/3b82f6/ffffff?text=PM+आवास"},{"id":"service-3","type":"card","title":"मनरेगा","description":"ग्रामीण कामगारांसाठी रोजगार हमी योजना","icon":"briefcase","link":"#","image":"https://via.placeholder.com/400x300/3b82f6/ffffff?text=मनरेगा"},{"id":"service-4","type":"card","title":"स्वच्छ भारत","description":"स्वच्छता आणि आरोग्यासाठी स्वच्छ भारत मिशन","icon":"trash","link":"#","image":"https://via.placeholder.com/400x300/3b82f6/ffffff?text=स्वच्छ+भारत"},{"id":"service-5","type":"card","title":"आयुष्मान भारत","description":"सर्व नागरिकांसाठी आरोग्य विमा योजना","icon":"heart","link":"#","image":"https://via.placeholder.com/400x300/3b82f6/ffffff?text=आयुष्मान"},{"id":"service-6","type":"card","title":"पीएम किसान","description":"शेतकऱ्यांसाठी थेट आय समर्थन","icon":"tractor","link":"#","image":"https://via.placeholder.com/400x300/3b82f6/ffffff?text=PM+किसान"}],"columns":3},"backgroundColor":"#ffffff","textColor":"#1e293b","isVisible":true,"displayOrder":1},
  {"sectionType":"TEAM_MEMBERS","layoutType":"GRID","title":"आमचे निर्वाचित प्रतिनिधी","subtitle":"समर्पणाने समुदायाची सेवा","content":{"items":[{"id":"member-1","type":"card","title":"सरपंच","subtitle":"[सरपंच नाव]","description":"पंचायतीचे प्रमुख, समुदाय विकास उपक्रमांचे नेतृत्व करत आहेत","image":"https://via.placeholder.com/300x300/1e3a8a/ffffff?text=सरपंच","link":"#"},{"id":"member-2","type":"card","title":"उप-सरपंच","subtitle":"[उप-सरपंच नाव]","description":"शासन आणि प्रशासनात मदत करणारे उप-सरपंच","image":"https://via.placeholder.com/300x300/3b82f6/ffffff?text=उप-सरपंच","link":"#"},{"id":"member-3","type":"card","title":"वार्ड सदस्य","subtitle":"[वार्ड सदस्य नाव]","description":"पंचायत निर्णयांमध्ये वार्ड हितांचे प्रतिनिधित्व करणे","image":"https://via.placeholder.com/300x300/60a5fa/ffffff?text=वार्ड+सदस्य","link":"#"}],"columns":3},"backgroundColor":"#f8fafc","textColor":"#1e293b","isVisible":true,"displayOrder":2},
  {"sectionType":"NEWS_FEED","layoutType":"GRID","title":"ताज्या बातम्या आणि घोषणा","subtitle":"गावातील क्रियाकलापांबद्दल माहिती रहा","content":{"items":[{"id":"news-1","type":"card","title":"ग्रामसभा बैठक","subtitle":"या महिन्याची 15 तारीख","description":"गाव विकास आणि नागरिक चिंतांवर चर्चा करण्यासाठी मासिक ग्रामसभा बैठक","image":"https://via.placeholder.com/400x300/1e3a8a/ffffff?text=ग्रामसभा","link":"#"},{"id":"news-2","type":"card","title":"सरकारी योजना अर्ज","subtitle":"अंतिम तारीख: महिन्याचा शेवट","description":"पीएम आवास योजना आणि इतर कल्याणकारी योजनांसाठी अर्ज करा","image":"https://via.placeholder.com/400x300/3b82f6/ffffff?text=योजना","link":"#"},{"id":"news-3","type":"card","title":"आरोग्य शिबिर","subtitle":"पुढील आठवडा","description":"आरोग्य विभागाद्वारे आयोजित निःशुल्क आरोग्य तपासणी शिबिर","image":"https://via.placeholder.com/400x300/60a5fa/ffffff?text=आरोग्य+शिबिर","link":"#"}],"columns":3},"backgroundColor":"#ffffff","textColor":"#1e293b","isVisible":true,"displayOrder":3}
]}',
'professional-blue', 10, true, true, true
WHERE NOT EXISTS (SELECT 1 FROM section_templates WHERE name = 'संक्षिप्त सेवा टेम्प्लेट' AND language = 'mr' AND is_page_template = true);

-- Template 2: Compact Information Template (Marathi) - 3 sections
INSERT INTO section_templates (name, description, category, language, template_data, color_theme, display_order, is_active, is_system, is_page_template) 
SELECT 'संक्षिप्त माहिती टेम्प्लेट', '3 पूर्व-कॉन्फिगर केलेल्या विभागांसह अतिशय संक्षिप्त पंचायत वेबसाइट टेम्प्लेट - आकडेवारी, सेवा आणि टीम', 'Full Page', 'mr',
'{"sections":[
  {"sectionType":"STATISTICS_SECTION","layoutType":"GRID","title":"गावाची मुख्य माहिती","subtitle":"एका नजरेने","content":{"items":[{"id":"stat-1","type":"stat","title":"लोकसंख्या","value":"5000+","label":"रहिवासी","icon":"users"},{"id":"stat-2","type":"stat","title":"कुटुंबे","value":"1200+","label":"कुटुंबे","icon":"building"},{"id":"stat-3","type":"stat","title":"क्षेत्र","value":"25","label":"चौ.किमी","icon":"map-pin"},{"id":"stat-4","type":"stat","title":"प्रकल्प","value":"45+","label":"पूर्ण","icon":"award"}],"columns":4},"backgroundColor":"#f0fdf4","textColor":"#14532d","isVisible":true,"displayOrder":0},
  {"sectionType":"CARD_SECTION","layoutType":"GRID","title":"मुख्य सेवा","subtitle":"नागरिकांसाठी आवश्यक सेवा","content":{"items":[{"id":"service-1","type":"card","title":"जन्म प्रमाणपत्र","description":"ऑनलाइन जन्म प्रमाणपत्र सेवा","icon":"file-text","link":"#","image":"https://via.placeholder.com/400x300/166534/ffffff?text=जन्म+प्रमाणपत्र"},{"id":"service-2","type":"card","title":"पीएम आवास","description":"गृहनिर्माण योजना","icon":"home","link":"#","image":"https://via.placeholder.com/400x300/22c55e/ffffff?text=PM+आवास"},{"id":"service-3","type":"card","title":"मनरेगा","description":"रोजगार हमी योजना","icon":"briefcase","link":"#","image":"https://via.placeholder.com/400x300/86efac/ffffff?text=मनरेगा"},{"id":"service-4","type":"card","title":"आयुष्मान","description":"आरोग्य विमा योजना","icon":"heart","link":"#","image":"https://via.placeholder.com/400x300/166534/ffffff?text=आयुष्मान"}],"columns":4},"backgroundColor":"#ffffff","textColor":"#166534","isVisible":true,"displayOrder":1},
  {"sectionType":"TEAM_MEMBERS","layoutType":"GRID","title":"पंचायत प्रतिनिधी","subtitle":"आमचे नेते","content":{"items":[{"id":"member-1","type":"card","title":"सरपंच","subtitle":"[सरपंच नाव]","description":"पंचायतीचे प्रमुख","image":"https://via.placeholder.com/300x300/166534/ffffff?text=सरपंच","link":"#"},{"id":"member-2","type":"card","title":"उप-सरपंच","subtitle":"[उप-सरपंच नाव]","description":"उप-प्रमुख","image":"https://via.placeholder.com/300x300/22c55e/ffffff?text=उप-सरपंच","link":"#"},{"id":"member-3","type":"card","title":"वार्ड सदस्य","subtitle":"[वार्ड सदस्य नाव]","description":"वार्ड प्रतिनिधी","image":"https://via.placeholder.com/300x300/86efac/ffffff?text=वार्ड+सदस्य","link":"#"}],"columns":3},"backgroundColor":"#f0fdf4","textColor":"#14532d","isVisible":true,"displayOrder":2}
]}',
'forest-green', 11, true, true, true
WHERE NOT EXISTS (SELECT 1 FROM section_templates WHERE name = 'संक्षिप्त माहिती टेम्प्लेट' AND language = 'mr' AND is_page_template = true);

-- Template 3: Compact Services & Gallery Template (Marathi) - 5 sections
INSERT INTO section_templates (name, description, category, language, template_data, color_theme, display_order, is_active, is_system, is_page_template) 
SELECT 'सेवा आणि गॅलरी टेम्प्लेट', '5 पूर्व-कॉन्फिगर केलेल्या विभागांसह संक्षिप्त पंचायत वेबसाइट टेम्प्लेट - आकडेवारी, सेवा, गॅलरी, बातम्या आणि सोशल मीडिया', 'Full Page', 'mr',
'{"sections":[
  {"sectionType":"STATISTICS_SECTION","layoutType":"GRID","title":"गावाची माहिती","subtitle":"मुख्य आकडेवारी","content":{"items":[{"id":"stat-1","type":"stat","title":"लोकसंख्या","value":"5000+","label":"रहिवासी","icon":"users"},{"id":"stat-2","type":"stat","title":"कुटुंबे","value":"1200+","label":"कुटुंबे","icon":"building"},{"id":"stat-3","type":"stat","title":"क्षेत्र","value":"25","label":"चौ.किमी","icon":"map-pin"}],"columns":3},"backgroundColor":"#f0fdfa","textColor":"#0d9488","isVisible":true,"displayOrder":0},
  {"sectionType":"CARD_SECTION","layoutType":"GRID","title":"नागरिक सेवा","subtitle":"सरकारी योजना आणि सेवा","content":{"items":[{"id":"service-1","type":"card","title":"जन्म प्रमाणपत्र","description":"ऑनलाइन जन्म प्रमाणपत्र सेवा","icon":"file-text","link":"#","image":"https://via.placeholder.com/400x300/0d9488/ffffff?text=जन्म+प्रमाणपत्र"},{"id":"service-2","type":"card","title":"पीएम आवास","description":"गृहनिर्माण योजना","icon":"home","link":"#","image":"https://via.placeholder.com/400x300/14b8a6/ffffff?text=PM+आवास"},{"id":"service-3","type":"card","title":"मनरेगा","description":"रोजगार हमी योजना","icon":"briefcase","link":"#","image":"https://via.placeholder.com/400x300/5eead4/ffffff?text=मनरेगा"},{"id":"service-4","type":"card","title":"स्वच्छ भारत","description":"स्वच्छता मिशन","icon":"trash","link":"#","image":"https://via.placeholder.com/400x300/0d9488/ffffff?text=स्वच्छ+भारत"}],"columns":4},"backgroundColor":"#ffffff","textColor":"#0d9488","isVisible":true,"displayOrder":1},
  {"sectionType":"IMAGE_GALLERY","layoutType":"GRID","title":"विकास कार्य","subtitle":"गावातील प्रकल्प आणि कार्य","content":{"items":[{"id":"gallery-1","type":"gallery_item","title":"रस्ता बांधकाम","description":"नवीन रस्ता प्रकल्प","image":"https://via.placeholder.com/600x400/0d9488/ffffff?text=रस्ता+प्रकल्प"},{"id":"gallery-2","type":"gallery_item","title":"पाणीपुरवठा","description":"पाणी प्रकल्प","image":"https://via.placeholder.com/600x400/14b8a6/ffffff?text=पाणी+प्रकल्प"},{"id":"gallery-3","type":"gallery_item","title":"शाळा इमारत","description":"शिक्षण प्रकल्प","image":"https://via.placeholder.com/600x400/5eead4/ffffff?text=शाळा+प्रकल्प"},{"id":"gallery-4","type":"gallery_item","title":"आरोग्य केंद्र","description":"आरोग्य सुविधा","image":"https://via.placeholder.com/600x400/0d9488/ffffff?text=आरोग्य+केंद्र"}],"columns":4},"backgroundColor":"#f0fdfa","textColor":"#0d9488","isVisible":true,"displayOrder":2},
  {"sectionType":"NEWS_FEED","layoutType":"GRID","title":"ताज्या बातम्या","subtitle":"गावातील नवीनतम माहिती","content":{"items":[{"id":"news-1","type":"card","title":"ग्रामसभा बैठक","subtitle":"या महिन्यात","description":"मासिक ग्रामसभा बैठक","image":"https://via.placeholder.com/400x300/0d9488/ffffff?text=ग्रामसभा","link":"#"},{"id":"news-2","type":"card","title":"योजना अर्ज","subtitle":"खुले आहेत","description":"सरकारी योजनांसाठी अर्ज करा","image":"https://via.placeholder.com/400x300/14b8a6/ffffff?text=योजना","link":"#"}],"columns":2},"backgroundColor":"#ffffff","textColor":"#0d9488","isVisible":true,"displayOrder":3},
  {"sectionType":"CARD_SECTION","layoutType":"ROW","title":"आमच्याशी जोडा","subtitle":"सोशल मीडियावर आम्हाला फॉलो करा","content":{"items":[{"id":"social-1","type":"card","title":"Facebook","description":"अपडेटसाठी","icon":"facebook","link":"https://facebook.com/panchayat","image":"https://via.placeholder.com/64x64/1877f2/ffffff?text=FB"},{"id":"social-2","type":"card","title":"WhatsApp","description":"गटात सामील व्हा","icon":"message-circle","link":"https://wa.me/1234567890","image":"https://via.placeholder.com/64x64/25d366/ffffff?text=WA"}],"columns":2},"backgroundColor":"#f0fdfa","textColor":"#0d9488","isVisible":true,"displayOrder":4}
]}',
'deep-teal', 12, true, true, true
WHERE NOT EXISTS (SELECT 1 FROM section_templates WHERE name = 'सेवा आणि गॅलरी टेम्प्लेट' AND language = 'mr' AND is_page_template = true);

-- Template 4: Minimal Services Template (Marathi) - 3 sections
INSERT INTO section_templates (name, description, category, language, template_data, color_theme, display_order, is_active, is_system, is_page_template) 
SELECT 'किमान सेवा टेम्प्लेट', '3 पूर्व-कॉन्फिगर केलेल्या विभागांसह अतिशय किमान पंचायत वेबसाइट टेम्प्लेट - सेवा, टीम आणि बातम्या', 'Full Page', 'mr',
'{"sections":[
  {"sectionType":"CARD_SECTION","layoutType":"GRID","title":"नागरिक सेवा","subtitle":"सरकारी योजना आणि सेवा","content":{"items":[{"id":"service-1","type":"card","title":"जन्म प्रमाणपत्र","description":"ऑनलाइन जन्म प्रमाणपत्र सेवा","icon":"file-text","link":"#","image":"https://via.placeholder.com/400x300/ec4899/ffffff?text=जन्म+प्रमाणपत्र"},{"id":"service-2","type":"card","title":"पीएम आवास योजना","description":"गृहनिर्माण योजना","icon":"home","link":"#","image":"https://via.placeholder.com/400x300/f472b6/ffffff?text=PM+आवास"},{"id":"service-3","type":"card","title":"मनरेगा","description":"रोजगार हमी योजना","icon":"briefcase","link":"#","image":"https://via.placeholder.com/400x300/f9a8d4/ffffff?text=मनरेगा"},{"id":"service-4","type":"card","title":"आयुष्मान भारत","description":"आरोग्य विमा योजना","icon":"heart","link":"#","image":"https://via.placeholder.com/400x300/ec4899/ffffff?text=आयुष्मान"},{"id":"service-5","type":"card","title":"स्वच्छ भारत","description":"स्वच्छता मिशन","icon":"trash","link":"#","image":"https://via.placeholder.com/400x300/f472b6/ffffff?text=स्वच्छ+भारत"},{"id":"service-6","type":"card","title":"पीएम किसान","description":"शेतकरी योजना","icon":"tractor","link":"#","image":"https://via.placeholder.com/400x300/f9a8d4/ffffff?text=PM+किसान"}],"columns":3},"backgroundColor":"#ffffff","textColor":"#831843","isVisible":true,"displayOrder":0},
  {"sectionType":"TEAM_MEMBERS","layoutType":"GRID","title":"पंचायत प्रतिनिधी","subtitle":"आमचे नेते","content":{"items":[{"id":"member-1","type":"card","title":"सरपंच","subtitle":"[सरपंच नाव]","description":"पंचायतीचे प्रमुख","image":"https://via.placeholder.com/300x300/ec4899/ffffff?text=सरपंच","link":"#"},{"id":"member-2","type":"card","title":"उप-सरपंच","subtitle":"[उप-सरपंच नाव]","description":"उप-प्रमुख","image":"https://via.placeholder.com/300x300/f472b6/ffffff?text=उप-सरपंच","link":"#"},{"id":"member-3","type":"card","title":"वार्ड सदस्य","subtitle":"[वार्ड सदस्य नाव]","description":"वार्ड प्रतिनिधी","image":"https://via.placeholder.com/300x300/f9a8d4/ffffff?text=वार्ड+सदस्य","link":"#"}],"columns":3},"backgroundColor":"#fdf2f8","textColor":"#831843","isVisible":true,"displayOrder":1},
  {"sectionType":"NEWS_FEED","layoutType":"GRID","title":"ताज्या बातम्या","subtitle":"गावातील नवीनतम माहिती","content":{"items":[{"id":"news-1","type":"card","title":"ग्रामसभा बैठक","subtitle":"या महिन्यात","description":"मासिक ग्रामसभा बैठक गाव विकासावर चर्चा करण्यासाठी","image":"https://via.placeholder.com/400x300/ec4899/ffffff?text=ग्रामसभा","link":"#"},{"id":"news-2","type":"card","title":"सरकारी योजना अर्ज","subtitle":"खुले आहेत","description":"पीएम आवास आणि इतर योजनांसाठी अर्ज करा","image":"https://via.placeholder.com/400x300/f472b6/ffffff?text=योजना","link":"#"},{"id":"news-3","type":"card","title":"आरोग्य शिबिर","subtitle":"पुढील आठवडा","description":"निःशुल्क आरोग्य तपासणी शिबिर","image":"https://via.placeholder.com/400x300/f9a8d4/ffffff?text=आरोग्य+शिबिर","link":"#"}],"columns":3},"backgroundColor":"#ffffff","textColor":"#831843","isVisible":true,"displayOrder":2}
]}',
'warm-pink', 13, true, true, true
WHERE NOT EXISTS (SELECT 1 FROM section_templates WHERE name = 'किमान सेवा टेम्प्लेट' AND language = 'mr' AND is_page_template = true);

